# Base image
FROM python:3.10

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Start Celery worker
CMD ["celery", "-A", "main.app", "worker", "--loglevel=info"]
