# Base image
FROM python:3.10

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . ./

# Start Celery worker
CMD ["celery", "-A", "main.app", "worker", "--loglevel=info"]
