version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/tmp/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
    ports:
      - "8081:8081"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network

  db_api:
    build: ./services/db/
    container_name: db_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://root:example@mongo:27017"
    volumes:
      - ./services/db:/app
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - app-network

  model_api:
    build: ./services/model_api/
    container_name: model_app
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    environment:
      DB_URL: "http://db_app:8000"
      REDIS_HOST: "redis"
    volumes:
      - ./services/model_api:/app
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
    networks:
      - app-network

  model_runner:
    build:
      context: ./services/model_api/
      dockerfile: Dockerfile.worker
    container_name: model_runner
    environment:
      REDIS_HOST: "redis"
      DB_URL: "http://db_app:8000"
    volumes:
      - ./services/model_api:/app
    command: ["celery", "-A", "model_runner.app", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - model_api
    restart: always
    networks:
      - app-network

  data_api:
    build: ./services/data_api/
    container_name: data_app
    restart: always
    ports:
      - "8002:8002"
    depends_on:
      - mongo
    volumes:
      - ./services/data_api:/app
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]
    networks:
      - app-network

  ui:
    container_name: ui_app
    build: ./services/ui/
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_URL: "http://db_app:8000"
      MODEL_API_URL: "http://model_app:8001"
      DATA_API_URL: "http://data_app:8002"
      NEXT_PUBLIC_API_URL: "http://localhost:3000"
    volumes:
      - ./services/ui:/app
      - /app/node_modules
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
