version: '3.8'

services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/tmp/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017
    ports:
      - "8081:8081"
    networks:
      - app-network

  api:
    build:
      context: ./
      dockerfile: ./api.dockerfile
    container_name: api_app
    restart: always
    ports:
      - "8002:8002"
    depends_on:
      - mongo
    volumes:
      - ./data/:/app/data
      - ./toktagger:/app/toktagger
      - ${CUSTOM_SCRIPT:-./toktagger/api/run.py}:/app/run.py
      - ~/.sal/:/root/.sal
    environment:
      MONGO_URL: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017"
      UDA_HOST: "uda2.mast.l"
      UDA_META_PLUGINNAME: "MASTU_DB"
      UDA_METANEW_PLUGINNAME: "MAST_DB"
      SAL_HOST: "https://sal.jetdata.eu"
      MODEL_STORAGE: "/app/data/models"
      API_URL: "http://api_app:8002"
      RELOAD: "true"
      WORKERS: "1"
    working_dir: /app
    command: ["python", "run.py"]
    networks:
      - app-network

  ui:
    container_name: ui_app
    build: ./toktagger/ui/
    ports:
      - "5173:5173"
    environment:
      PORT: 5173
      NODE_ENV: development
      VITE_DATA_API_URL: "http://localhost:8002"
    volumes:
      - ./toktagger/ui:/app
      - /app/node_modules
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
